### ISSUE TITLE
run through draft diversity lab

### ISSUE THREAD

**Issue by adw96** [adw96/stamps2018#24]
@paulinetrinh  first (while @bryandmartin works on corncob), then I'll revise and ask @bryandmartin  to look through it

**Comment by bryandmartin** [comment]
@adw96 saw there was a pull request. Ready for the next read through?

**Comment by adw96** [comment]
@bryandmartin One more thing to do, then I'll give the 👍

**Comment by adw96** [comment]
@paulinetrinh I made some changes to the end to include beta diversity;  I added some functionality in DivNet too.  Could you give it another run through? Thanks!

**Comment by paulinetrinh** [comment]
Yay done.
