### ISSUE TITLE
look over CORNCOB lecture

### ISSUE THREAD

**Issue by adw96** [adw96/stamps2018#3]
@bryandmartin 

1. Could you look over estimation/abundance-lecture and tell me if there's anything you want me to add/subtract? 
2. Could you please send me a screenshot of the output for slide 10?
3. Any other screenshots of output would be great. 

It might be better for you to fork and submit a pull request -- but could you make comments to tell me what you've changed? Thanks!

**Comment by bryandmartin** [comment]
@adw96 See #4

**Comment by adw96** [comment]
Wonderful, thank you!
